name: Build and Test

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: "ubuntu-22.04"
    steps:
    - name: "Setup QEMU"
      uses: "docker/setup-qemu-action@v2"
    - name: "Setup builder"
      uses: "docker/setup-buildx-action@v2"
    - name: "Checkout"
      uses: "actions/checkout@v3"
    - name: "Build and push image"
      uses: "docker/build-push-action@v3"
      with:
        context: .
        file: Dockerfile
        platforms: linux/arm64,linux/amd64
        outputs: type=cacheonly
        tags: lightsparkdev/go-sdk:latest


  test:
    runs-on: "ubuntu-22.04"
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21

    - name: Build
      run: go build -v ./...

    - name: Build LNURL Server
      run: go build -v
      working-directory: examples/lnurl-server
    
    - name: Build UMA Server
      run: go build -v
      working-directory: examples/uma-server
    
    - name: Build Remote Signing Server
      run: go build -v
      working-directory: examples/remote-signing-server

    - name: Test
      run: go test -v -tags='!integration' ./...

